image: python:3.12.3-slim

variables:
  TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_PIPELINE_ID

stages:
  - publish
  - deploy

publish:
  image: docker:latest
  stage: publish
  cache:
    key: $CI_PROJECT_DIR
    paths:
      - vendor/
    policy: pull
  tags:
    - jjmall-runner
  services:
    - docker:dind
  script:
    - docker build -t $TAG .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $TAG
  only:
    refs:
      - staging
      - production

deployment:
  image: alpine:latest
  stage: deploy
  environment:
    name: $CI_COMMIT_REF_NAME
  tags:
    - jjmall-runner
  before_script:
    - apk update && apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
    - ssh $SERVER_USER@$SERVER_IP "docker pull $TAG"
    - ssh $SERVER_USER@$SERVER_IP "docker service update --image $TAG --force --with-registry-auth $SERVICE"
  only:
    refs:
      - staging
      - production
